# Render Blueprint for Smartphone Price Tracker
# This file defines all services needed for deployment on Render.com

databases:
  - name: smartphone-price-tracker-db

services:

  # Redis Service
  - type: redis
    name: smartphone-price-tracker-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

  # Main Web Service (for API and dashboard if needed)
  - type: web
    name: smartphone-price-tracker-web
    env: python3
    plan: starter  # Free tier, upgrade for production
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: smartphone-price-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: smartphone-price-tracker-redis
          property: connectionString
    healthCheckPath: /health

  # Background Worker for Scraping
  - type: worker
    name: smartphone-price-tracker-worker
    env: python3
    plan: starter
    buildCommand: pip install -r requirements-render.txt
    startCommand: python worker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: smartphone-price-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: smartphone-price-tracker-redis
          property: connectionString

  # Cron Job for Scheduled Tasks
  - type: cron
    name: smartphone-price-tracker-scheduler
    env: python3
    plan: starter
    buildCommand: pip install -r requirements-render.txt
    schedule: "0 6 * * 1"  # Run every Monday at 6 AM UTC
    startCommand: python cli.py scrape && python cli.py report
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: smartphone-price-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: smartphone-price-tracker-redis
          property: connectionString

# Note: Set these environment variables manually in each service:
# SMTP_USERNAME, SMTP_PASSWORD, EMAIL_FROM, EMAIL_TO
# Optional: EBAY_CLIENT_ID, EBAY_CLIENT_SECRET, BACK_MARKET_API_KEY